### ISSUE TITLE
[Feature Request] Pitch & Yaw lock

### ISSUE THREAD

**Issue by Julienraptor01** [WinterWolfSV/Pitch_And_Yaw_Control#1]
Could you add a pitch and yaw lock ?
Just so that you can set them perfectly and then once you lock them, even if you move the mouse, they can't be modified
This would help with screenshots where you raise the shield or attack with a weapon

**Comment by WinterWolfSV** [comment]
Done! The newest release (1.0.4) now has this feature implemented. Thanks for the feedback!

**Comment by Julienraptor01** [comment]
Thanks 👍
