### ISSUE TITLE
[BUG] Commands aren't registered in Multiplayer

### ISSUE THREAD

**Issue by Julienraptor01** [WinterWolfSV/Pitch_And_Yaw_Control#3]
![image](https://user-images.githubusercontent.com/49841713/223745918-776d03a9-e6de-4d9f-8308-c591f9da0ca3.png)
as this shows the commands aren't present in Multiplayer even tho the mod is working in multiplayer

**Comment by WinterWolfSV** [comment]
Fixed in version 1.0.5
