### ISSUE TITLE
[BUG] /angle isn't present ?

### ISSUE THREAD

**Issue by Julienraptor01** [WinterWolfSV/Pitch_And_Yaw_Control#4]
![image](https://user-images.githubusercontent.com/49841713/223746903-76ad7a80-50f6-4b41-bd1f-b0bf051aa134.png)
![image](https://user-images.githubusercontent.com/49841713/223746957-74f14649-9224-430b-bbe0-b00150f3bb20.png)
For some reason it look like /angle doesn't exist

**Comment by WinterWolfSV** [comment]
Fixed in version 1.0.5
